schema_version = "1.0.0"

id = "para_rig"
version = "1.0.0"
name = "ParaRig"
tagline = "Auto-generate draggable slider rigs and Driver bindings"
maintainer = "Zosuya <pararig@zusuya.cc>"
type = "add-on"
website = "https://github.com/Zosuya/ParaRig"

license = [
  "SPDX:GPL-3.0-or-later",
]

blender_version_min = "4.2.0"

tags = ["Rigging"]
